### ISSUE TITLE
Organização do Projeto

### ISSUE THREAD

**Issue by marsicanogeorge** [mdsreq-fga-unb/2023.2-NutriPlanner#10]
NENHUM PAPEL OU ATRIBUIÇÕES DE ER.
REFAÇAM

![image](https://github.com/mdsreq-fga-unb/2023.2-NutriPlanner/assets/68402547/683c9828-c858-4200-b5cc-840db835e49a)

**Comment by MatsFidelis** [comment]
Projeto revisado e atualizado, o PR que resolve esta issue é o #18

**Comment by marsicanogeorge** [comment]
> pessoal, não inventem, facilitem, simplifiquem. Quais são as atribuições / atividades de ER ?!

![image](https://github.com/mdsreq-fga-unb/2023.2-NutriPlanner/assets/68402547/f3cfb54a-166c-40da-b6f8-64de1a5b062f)
