### ISSUE TITLE
Planejamento das Fases e/ou Iterações do Projeto

### ISSUE THREAD

**Issue by marsicanogeorge** [mdsreq-fga-unb/2023.2-NutriPlanner#11]
1. INCOMPLETO. DEVE ESTAR PLANEJADO ATÉ O FINAL DA DISCIPLINA

![image](https://github.com/mdsreq-fga-unb/2023.2-NutriPlanner/assets/68402547/020bcfc2-d548-4f37-8b64-228dfc559959)

**Comment by MatsFidelis** [comment]
Alterações revisadas e já estão no contexto de desenvolvimento. PR que fecha esta issue #19

**Comment by marsicanogeorge** [comment]
> Vcs vão fazer apenas um Ciclo de "Prototipação, Refinamento e Teste"? E dois de Construção? É isso mesmo? Tá com cara de CASCATA esse processo, hein?

![image](https://github.com/mdsreq-fga-unb/2023.2-NutriPlanner/assets/68402547/6b6e3214-8bd3-48b8-84a4-46f09647e8c0)

**Comment by MatsFidelis** [comment]
Pull Request referente a esta issue ja foi revisado e devidamente implementado na branch de desenvolvimento.
