### ISSUE TITLE
Matriz de Comunicação

### ISSUE THREAD

**Issue by marsicanogeorge** [mdsreq-fga-unb/2023.2-NutriPlanner#12]
1. ESTARÃO COM O CLIENTE UMA VEZ A CADA 15 DIAS? COMO ISSO ENCAIXA NO RAD?!
2. ESTARÃO COM O PROF A CADA 30 DIAS?!

AJUSTEM

**Comment by MatsFidelis** [comment]
Alterações realizadas e Revisadas !! 
Issue sendo finalizada.
