### ISSUE TITLE
Processo de Desenvolvimento

### ISSUE THREAD

**Issue by marsicanogeorge** [mdsreq-fga-unb/2023.2-NutriPlanner#13]
**Planejamento de requisitos**
1. VCS VÃO UTILIZAR USM OU BACKLOG?

![image](https://github.com/mdsreq-fga-unb/2023.2-NutriPlanner/assets/68402547/1600cc6b-0560-4fd0-a7df-b7fa360fb75b)

**User Design**
1. NÃO HAVERÁ ELICITAÇÃO E DESCOBERTA, E ANÁLISE E CONSENSO?
2. NÃO HAVERÁ VER E VAL?
3. APENAS REPRESENTAÇÃO?

![image](https://github.com/mdsreq-fga-unb/2023.2-NutriPlanner/assets/68402547/665d3c09-c033-46d7-b15d-a35efaed3592)

**Comment by Maliz30** [comment]
A elicitação e descoberta, análise e consenso e verificação e validação foram corrigidas, mas estão em tabelas diferentes:

- elicitação e descoberta, análise e consenso:
![image](https://github.com/mdsreq-fga-unb/2023.2-NutriPlanner/assets/105389239/fcd4dcea-0cb3-434f-879f-ed50c458b132)


- verificação e validação:
![image](https://github.com/mdsreq-fga-unb/2023.2-NutriPlanner/assets/105389239/73bde235-0d93-4257-9dbd-998a0b7f87f9)
