### ISSUE TITLE
Entrega 2

### ISSUE THREAD

**Issue by Maliz30** [mdsreq-fga-unb/2023.2-NutriPlanner#20]
- [x] Backlog priorizado
  - [x] MVP definido
  - [x] Issues da entrega 1 encerradas

GitPages finalizado
>   - [x] Lições aprendidas
>   - [x] História da facção e brasão
>   - [x] MVP
>   - [x] Backlog com granularidades

- [x] Vídeo de entrega

**Comment by MatsFidelis** [comment]
Atividades pendentes já realizadas. Entregas referentes a unidade 02 foram finalizadas e já revisadas pela equipe, e publicadas nos seguintes PR's -> #21 ; #23
