### ISSUE TITLE
[US26] - Eu, como nutricionista, quero ser capaz de visualizar as informações de um paciente cadastrado no sistema, para poder consultar as informações. 

### ISSUE THREAD

**Issue by Maliz30** [mdsreq-fga-unb/2023.2-NutriPlanner#56]
### Descrição:
Eu, como nutricionista, quero ser capaz de visualizar as informações de um paciente cadastrado no sistema, para poder consultar as informações.

### Tarefas:

- [x] O sistema deve mostrar nome, e-mail, telefone, endereço, altura, peso e medidas corporais no perfil do paciente selecionado.

### Critérios de aceitação:

- O sistema deve mostrar nome, e-mail, telefone, endereço, altura, peso e medidas corporais no perfil do paciente selecionado.

### Tela (caso não tenha, delete essa parte)
![image](https://github.com/mdsreq-fga-unb/2023.2-NutriPlanner/assets/105389239/e2e0fb2f-790f-4ba3-8b07-d52fa8fedf4f)

### DoR - Definition of Ready 

A US só poderá ser desenvolvida se atender aos requisitos abaixo:

- [x] O Requisito possui está declarado de forma não ambígua?
- [x] O Requisito pode ser realizado dada a realidade do projeto (restrições de tempo e técnicas)?
- [x] O Requisito possui informação necessária para ser trabalhado? 
- [x] O Requisito possui critérios de aceitação?
- [x] O protótipo foi validado pelo cliente?
- [x] O requisito segue os critérios de priorização?

**Comment by LucasSpinosa** [comment]
Quando estiver tudo pronto, atualizar os cards de aniversariantes para o link no card levar para a visualização da página do paciente em questão.
