### ISSUE TITLE
[REQUISITOS] Criação do Backlog a partir da metodologia do Safe

### ISSUE THREAD

**Issue by MatsFidelis** [mdsreq-fga-unb/2023.2-NutriPlanner#6]
## Descrição da Issue
A partir do estudo realizado sobre a metodologia do Safe, aplicar o que a equipe entendeu e realizar a criação de um backlog contendo os requisitos funcionais (RF's) e os requisitos não funcionais (RNF's)

## Tasks:
- [x] Realizar a criação do Backlog

## Critérios de Aceitação:
- [x] Estar estruturado de acordado com a metodologia Safe

## Milestone
Sprint 03

**Comment by MillenaQueiroz** [comment]
O backlog se encontra no miro
