### ISSUE TITLE
Problema

### ISSUE THREAD

**Issue by marsicanogeorge** [mdsreq-fga-unb/2023.2-NutriPlanner#7]
"Nota-se que, devido à falta de funcionários e **à falta de um software que atenda o seu negócio**, o cliente fica com toda a responsabilidade de estruturar essas informações para si, tendo que usar soluções próprias para suas necessidades, como Excel ou mesmo uma agenda física. Logo, percebe-se que uma solução em software pensada especificamente para o cliente facilitaria muito o seu ambiente de trabalho."

**à falta de um software que atenda o seu negócio**: falta de software não é problema organizacional. E, sim o aumento da demanda, aumento de dados para dar conta, etc.

**Comment by MatsFidelis** [comment]
Pull Request referente a esta issue ja foi revisado e devidamente implementado na branch de desenvolvimento.

**Comment by marsicanogeorge** [comment]
> tem dois problemas, aqui. qual é o problema?

![image](https://github.com/mdsreq-fga-unb/2023.2-NutriPlanner/assets/68402547/34d67ba7-f93d-43f2-923c-661d92a90df5)

**Comment by MatsFidelis** [comment]
Pull Request referente a esta issue ja foi revisado e devidamente implementado na branch de desenvolvimento.
