### ISSUE TITLE
Objetivos do Produto

### ISSUE THREAD

**Issue by marsicanogeorge** [mdsreq-fga-unb/2023.2-NutriPlanner#9]
"O objetivo central desse produto é ajudar profissionais da área de saúde que precisam organizar dietas para seus clientes de forma **prática e organizada**, ao contrário de métodos convencionais, como planilhas e agendas."

1. OS OBJETIVOS, PRINCIPAL E SECUNDÁRIOS, PRECISAM SER VERIFICÁVEIS.
2. APRESENTEM OBJETIVO PRINCIPAL E OBJETIVOS SECUNDÁRIOS.

REFAÇAM.

**Comment by MatsFidelis** [comment]
Alterações realizadas e Revisadas !! 
Issue sendo finalizada.

**Comment by marsicanogeorge** [comment]
Objetivos do Produto:
Esse produto será desenvolvido para ajudar profissionais da área de saúde, que muitas vezes perdem tempo realizando as dietas e treinos manualmente em planilhas. 

1. O objetivo principal desse produto é a geração de dietas/treinos e o seu envio por e-mail para os pacientes; 
> o software vai gerar as dietas e treinos?

3. Outro objetivo seria o cadastro do paciente na plataforma, o nutricionista terá liberdade de alterar as informações desse paciente ou se preferir excluir; 
> característica do produto, não é objetivo.

3. Também, o sistema apresentará funções de envio de e-mails, como e-mail para agendar consultas, ou quando for o aniversário do paciente ele receberá um e-mail de parabenização.
> característica do produto, não é objetivo.

**Comment by Leanddro13** [comment]
##  Objetivos do Produto:
**Objetivo principal:** o sistema deve auxiliar um negócio de consultoria de nutrição, tanto na parte de administração dos pacientes (envios de mensagens por e-mail, dados pessoais) quanto na parte de administração de consultas (geração e envio de dietas e treinos, agendamento de consultas).

**Objetivos Específicos:**

- Desenvolver um sistema que permita o cadastro e a administração eficiente das informações de pacientes.
- Implementar uma funcionalidade que permita nutricionistas e pacientes agendar consultas de forma fácil e conveniente, com opções de disponibilidade e lembretes.
- Criar uma ferramenta no sistema que possibilite a geração de planos de dieta personalizados com base nas necessidades de saúde e preferências dos pacientes.
- Desenvolver uma funcionalidade que permita a criação de planos de treino adaptados às metas e capacidades individuais dos pacientes.
- Integre um sistema de mensagens por e-mail no aplicativo para permitir a comunicação direta entre profissionais de saúde e pacientes, enviando informações importantes, lembretes de consultas e dicas de saúde.
